#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Batch SWC preprocessor

Pipeline per file:
  (1) Optional: limit depth (<= max_depth)
  (2) High-degree normalization (split deg=4; prune deg>4 to two thickest)
  (3) Collapse degree-2 nodes; re-orient; re-index; write SWC

Usage:
  python preprocess_swc.py /path/to/raw_swc /path/to/clean_swc \
      --max-depth 16 --root-parent 0 --drop-attrs
"""

from __future__ import annotations
import argparse
import os
from pathlib import Path
import sys
import math
import warnings
import pandas as pd
import numpy as np
from typing import Dict, List, Tuple, Set
from collections import deque

# progress bar (optional)
try:
    from tqdm import tqdm
except Exception:
    tqdm = None


# ---------- I/O helpers ----------

SWC_COLS = ['id','type','x','y','z','radius','parent']

def read_swc(path: Path) -> pd.DataFrame:
    """Robust SWC reader supporting whitespace or comma delimiters.

    Standard SWC lines: id type x y z radius parent (whitespace separated).
    Some data exports produce comma-separated lines or include extra trailing
    columns (which we ignore). This function attempts:
      1) pandas whitespace-delimited fast path
      2) fallback: detect comma usage or single-column parse -> manual tokenizer
    """
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", FutureWarning)
            df = pd.read_csv(
                path,
                comment='#',
                header=None,
                delim_whitespace=True,
                names=SWC_COLS,
                usecols=range(7),
                engine='python'
            )
        # If we only got a single column, likely comma-delimited input; trigger fallback
        if df.shape[1] == 1:
            raise ValueError("Whitespace parse produced single column; retry as CSV")
    except Exception:
        # Fallback manual parse: split on commas or whitespace
        print(f"[WARN] Fallback SWC parser used for {path}")
        rows: List[List[str]] = []
        malformed = 0
        with open(path, 'r') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                # Replace commas with spaces then split; handles mixed delimiters.
                parts = line.replace(',', ' ').split()
                if len(parts) < 7:
                    malformed += 1
                    continue
                rows.append(parts[:7])
        if not rows:
            raise ValueError(f"No valid SWC data rows parsed from {path}")
        if malformed:
            print(f"[WARN] Skipped {malformed} malformed line(s) in {path}")
        df = pd.DataFrame(rows, columns=SWC_COLS)

    # enforce dtypes (robust conversion)
    df['id'] = df['id'].astype(int)
    df['type'] = df['type'].astype(float).astype(int)
    for ax in ['x','y','z','radius']:
        df[ax] = df[ax].astype(float)
    df['parent'] = df['parent'].astype(int)
    return df

def write_swc(df: pd.DataFrame, path: Path, root_parent_value: int = 0) -> None:
    out = df.copy()
    out = out[['id','type','x','y','z','radius','parent']].sort_values('id')
    # ensure root parent is exactly root_parent_value
    roots = out['parent'] <= root_parent_value
    out.loc[roots, 'parent'] = root_parent_value
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w') as f:
        f.write("# cleaned SWC generated by preprocess_swc.py\n")
        out.to_csv(f, sep=' ', header=False, index=False, float_format="%.6f")


# ---------- Core structures ----------

class SWCTree:
    """In-memory SWC as nodes + children adjacency."""
    def __init__(self, df: pd.DataFrame, root_parent_value: int = 0):
        self.root_parent_value = int(root_parent_value)
        self.nodes: Dict[int, dict] = {
            int(r.id): {
                'type': int(r.type),
                'x': float(r.x), 'y': float(r.y), 'z': float(r.z),
                'radius': float(r.radius),
                'parent': int(r.parent)
            } for r in df.itertuples(index=False)
        }
        self.children: Dict[int, List[int]] = {}
        for nid, rec in self.nodes.items():
            p = rec['parent']
            if p > self.root_parent_value:
                self.children.setdefault(p, []).append(nid)
            self.children.setdefault(nid, self.children.get(nid, []))

    def roots(self) -> List[int]:
        return [nid for nid, r in self.nodes.items()
                if r['parent'] <= self.root_parent_value]

    def coord(self, u: int) -> np.ndarray:
        r = self.nodes[u]
        return np.array([r['x'], r['y'], r['z']], dtype=float)

    def delete_subtree(self, v: int) -> None:
        """Delete node v and all descendants."""
        stack = [v]
        to_del = []
        while stack:
            w = stack.pop()
            to_del.append(w)
            stack.extend(self.children.get(w, []))
        # detach and remove
        for w in to_del:
            pw = self.nodes[w]['parent']
            if pw in self.children and w in self.children[pw]:
                self.children[pw].remove(w)
            if w in self.children:
                del self.children[w]
            if w in self.nodes:
                del self.nodes[w]

    def add_node(self, ntype: int, xyz: np.ndarray, radius: float, parent: int) -> int:
        nid = (max(self.nodes.keys()) + 1) if self.nodes else 1
        self.nodes[nid] = {
            'type': int(ntype),
            'x': float(xyz[0]), 'y': float(xyz[1]), 'z': float(xyz[2]),
            'radius': float(radius),
            'parent': int(parent)
        }
        self.children.setdefault(nid, [])
        self.children.setdefault(parent, []).append(nid)
        return nid


# ---------- Step (1): depth limit ----------

def trim_to_max_depth(tree: SWCTree, max_depth: int | None) -> None:
    """
    Prune subtrees deeper than max_depth (edge hops) from each root.
    Semantics: root depth = 0; nodes kept if depth(u) <= max_depth.
    All children of nodes at depth == max_depth are deleted.
    """
    if max_depth is None:
        return
    max_depth = int(max_depth)

    for r in tree.roots():
        q: deque[tuple[int, int]] = deque([(r, 0)])
        visited: set[int] = set([r])   # trees shouldn't revisit, but safe

        while q:
            u, d = q.popleft()
            if d == max_depth:
                # delete entire subtrees of all current children (depth > max_depth)
                for c in list(tree.children.get(u, [])):
                    tree.delete_subtree(c)
                # do not enqueue deeper
                continue

            # enqueue children (depth + 1)
            for c in list(tree.children.get(u, [])):
                if c not in visited:
                    visited.add(c)
                    q.append((c, d + 1))


# ---------- Step (2): high-degree normalization ----------

def normalize_high_degree(
    tree: SWCTree,
    eps_scale: float = 0.1,
    new_node_type: int | None = None,
) -> None:
    """Split deg==4 into two deg==3; for deg>4 keep 2 thickest children, drop the rest."""
    rp = tree.root_parent_value

    def norm(v: np.ndarray) -> np.ndarray:
        n = np.linalg.norm(v)
        return v / n if n > 0 else v

    # First pass: prune deg>4 to top-2 by child radius
    candidates = [u for u in list(tree.nodes.keys())
                  if (tree.nodes[u]['parent'] > rp and len(tree.children.get(u, [])) >= 3)]
    for u in candidates:
        kids = list(tree.children.get(u, []))
        if len(kids) <= 3:
            continue
        kids_sorted = sorted(kids, key=lambda c: tree.nodes[c]['radius'], reverse=True)
        keep = set(kids_sorted[:2])
        for c in kids:
            if c not in keep:
                tree.delete_subtree(c)

    # Recompute: nodes with exactly 3 kids (non-root) → split
    splitters = [u for u in list(tree.nodes.keys())
                 if (tree.nodes[u]['parent'] > rp and len(tree.children.get(u, [])) == 3)]
    for u in splitters:
        kids = list(tree.children.get(u, []))
        if len(kids) != 3:
            continue
        p = tree.nodes[u]['parent']
        xu = tree.coord(u)
        xp = tree.coord(p)
        vp = norm(xp - xu)

        triples = []
        dists = []
        for c in kids:
            vc = norm(tree.coord(c) - xu)
            theta = float(math.acos(float(np.clip(np.dot(vp, vc), -1.0, 1.0))))
            triples.append((c, vc, theta))
            dists.append(np.linalg.norm(tree.coord(c) - xu))

        # furthest by angle stays attached to u
        c_far, v_far, _ = max(triples, key=lambda t: t[2])
        close = [t for t in triples if t[0] != c_far]
        (c1, v1, _), (c2, v2, _) = close
        local_scale = float(np.mean(dists)) if dists else 1.0
        eps = max(1e-6, eps_scale * local_scale)

        bis = v1 + v2
        if np.linalg.norm(bis) < 1e-9:
            bis = v1
        bis = norm(bis)

        new_type = tree.nodes[u]['type'] if new_node_type is None else int(new_node_type)
        new_rad = float(np.median([tree.nodes[u]['radius'], tree.nodes[c1]['radius'], tree.nodes[c2]['radius']]))
        up = tree.add_node(new_type, xu + eps * bis, new_rad, parent=u)

        # Rewire c1, c2 to up
        for c in (c1, c2):
            if c in tree.children[u]:
                tree.children[u].remove(c)
            tree.children[up].append(c)
            tree.nodes[c]['parent'] = up


# ---------- Step (3): collapse degree-2 (pure dicts, no networkx) ----------

def collapse_degree2(
    tree: SWCTree,
    keep_attrs: bool,
    root_parent_value: int,
    keep_parent_value: int
) -> pd.DataFrame:
    """
    Collapse degree-2 chains, then BFS to orient and re-index.
    Returns a simplified SWC DataFrame with columns SWC_COLS.
    """
    rp = root_parent_value

    # Build undirected neighbors
    neighbors: Dict[int, List[int]] = {u: [] for u in tree.nodes.keys()}
    for u, rec in tree.nodes.items():
        p = rec['parent']
        if p > rp:
            neighbors[u].append(p)
            neighbors[p].append(u)
        # children already in tree.children

    for u, kids in tree.children.items():
        for v in kids:
            if v not in neighbors[u]:
                neighbors[u].append(v)
            if u not in neighbors[v]:
                neighbors[v].append(u)

    degree = {u: len(neighbors[u]) for u in neighbors}
    roots = [u for u, r in tree.nodes.items() if r['parent'] <= rp]
    keepers: Set[int] = set(roots) | {u for u, d in degree.items() if d != 2}

    def walk_to_keeper(u: int, v: int) -> Tuple[int, List[int]]:
        path = [u, v]
        prev, cur = u, v
        while cur not in keepers:
            nbrs = neighbors[cur]
            nxt = nbrs[0] if nbrs[1] == prev else nbrs[1]
            prev, cur = cur, nxt
            path.append(cur)
        return cur, path

    # Discover simplified edges between keepers
    seen = set()
    simp_edges: List[Tuple[int, int]] = []
    for u in keepers:
        for v in neighbors[u]:
            a, b = (u, v) if u < v else (v, u)
            if (a, b) in seen:
                continue
            seen.add((a, b))
            if v in keepers:
                uu, ww = u, v
            else:
                w, _ = walk_to_keeper(u, v)
                uu, ww = u, w
            k0, k1 = (uu, ww) if uu < ww else (ww, uu)
            if (k0, k1) not in simp_edges:
                simp_edges.append((k0, k1))

    # Build simplified adjacency over keepers
    simp_adj: Dict[int, List[int]] = {k: [] for k in keepers}
    for a, b in simp_edges:
        simp_adj[a].append(b)
        simp_adj[b].append(a)

    # BFS orientation and re-indexing
    parent_of: Dict[int, int] = {}
    order: List[int] = []
    visited: Set[int] = set()
    from collections import deque
    for r in roots:
        if r not in simp_adj or r in visited:
            continue
        q = deque([r])
        parent_of[r] = keep_parent_value
        visited.add(r)
        while q:
            u = q.popleft()
            order.append(u)
            for v in simp_adj[u]:
                if v not in visited:
                    parent_of[v] = u
                    visited.add(v)
                    q.append(v)
    # disconnected components
    for k in simp_adj.keys():
        if k not in visited:
            q = deque([k])
            parent_of[k] = keep_parent_value
            visited.add(k)
            while q:
                u = q.popleft()
                order.append(u)
                for v in simp_adj[u]:
                    if v not in visited:
                        parent_of[v] = u
                        visited.add(v)
                        q.append(v)

    new_id = {oid: i for i, oid in enumerate(order, start=1)}

    rows = []
    for oid in order:
        r = tree.nodes[oid]
        if keep_attrs:
            t = int(r['type'])
            rad = float(r['radius'])
        else:
            t = 3  # generic neurite
            rad = 1.0
        rows.append({
            'id': new_id[oid],
            'type': t,
            'x': float(r['x']),
            'y': float(r['y']),
            'z': float(r['z']),
            'radius': rad,
            'parent': keep_parent_value if parent_of[oid] == keep_parent_value else new_id[parent_of[oid]],
        })

    out = pd.DataFrame(rows, columns=SWC_COLS)
    return out


# ---------- Re-root helper ----------

def _reroot_df_at_node(df: pd.DataFrame, root_nid: int, root_parent_value: int) -> pd.DataFrame:
    """BFS from root_nid, reassign parent column to orient tree from that node."""
    ids = set(df['id'].astype(int))
    if root_nid not in ids:
        raise ValueError(f"Root node {root_nid} not found in SWC data")
    # Build undirected adjacency from existing parent pointers
    adj: Dict[int, List[int]] = {int(nid): [] for nid in df['id']}
    for _, row in df.iterrows():
        nid, par = int(row['id']), int(row['parent'])
        if par in adj:
            adj[nid].append(par)
            adj[par].append(nid)
    # BFS from root_nid
    new_parent = {root_nid: root_parent_value}
    q = deque([root_nid])
    visited = {root_nid}
    while q:
        u = q.popleft()
        for v in adj[u]:
            if v not in visited:
                new_parent[v] = u
                visited.add(v)
                q.append(v)
    df = df.copy()
    df['parent'] = df['id'].apply(lambda nid: new_parent[int(nid)])
    return df


# ---------- One-shot cleaner ----------

def clean_swc_tree(
    df: pd.DataFrame,
    *,
    root_parent_value: int = 0,
    keep_parent_value: int = 0,
    max_depth: int | None = None,
    eps_scale: float = 0.1,
    keep_attrs: bool = True,
    root_mode: str = "parent",
) -> pd.DataFrame:
    """
    Full pipeline for one SWC file.

    New (collapse-first) order requested:
      1. Build in-memory tree
      2. Collapse degree-2 chains (early shrink) and re-index
      3. Depth pruning on collapsed tree (trim subtrees with depth > max_depth)
      4. High-degree normalization (split deg==4, prune deg>4) on trimmed tree
      5. Final collapse & re-index (remove any new internal degree-2 chains introduced by splitting)

    Notes / Trade-offs:
      - Collapsing early changes which nodes are considered branching for normalization; results may differ slightly
        from normalize-first ordering.
      - Normalization after depth trimming can introduce new nodes one hop deeper than their parent. We only split
        nodes whose parent depth < max_depth, so inserted node depth <= max_depth. If a parent is exactly at max_depth
        its children were already pruned and it won't be split.
      - Final collapse ensures synthetic node insertion does not leave residual internal degree-2 chains.
    """
    # (0) re-root if needed
    if root_mode == "index":
        df = _reroot_df_at_node(df, root_nid=1, root_parent_value=root_parent_value)

    # (1) initial tree
    tree_initial = SWCTree(df, root_parent_value=root_parent_value)

    # (2) early collapse (shrink linear chains before other passes)
    collapsed_df_early = collapse_degree2(
        tree_initial,
        keep_attrs=keep_attrs,
        root_parent_value=root_parent_value,
        keep_parent_value=keep_parent_value
    )

    # Rebuild tree from collapsed representation for subsequent passes
    tree = SWCTree(collapsed_df_early, root_parent_value=root_parent_value)

    # (3) depth pruning on collapsed tree
    if max_depth is not None:
        trim_to_max_depth(tree, max_depth=max_depth)

    # (4) high-degree normalization after depth enforcement
    normalize_high_degree(tree, eps_scale=eps_scale, new_node_type=None)

    # (Optional strict cap) If desired, re-run trim_to_max_depth here.

    # (5) final collapse & re-index (remove any introduced degree-2 chains)
    final_df = collapse_degree2(
        tree,
        keep_attrs=keep_attrs,
        root_parent_value=root_parent_value,
        keep_parent_value=keep_parent_value
    )
    return final_df


# ---------- Batch runner ----------

def iter_swc_files(in_dir: Path, recursive: bool) -> List[Path]:
    if recursive:
        return sorted(p for p in in_dir.rglob("*.swc") if p.is_file())
    else:
        return sorted(p for p in in_dir.glob("*.swc") if p.is_file())

def main():
    ap = argparse.ArgumentParser(description="Batch preprocess SWC trees.")
    ap.add_argument("input_dir", type=Path, help="Folder containing raw .swc files")
    ap.add_argument("output_dir", type=Path, help="Folder to write cleaned .swc files")
    ap.add_argument("--max-depth", type=int, default=None, help="Limit tree depth (edge hops) <= max_depth")
    ap.add_argument("--root-parent", type=int, default=0, choices=[0, -1], help="Parent value for roots in output SWC")
    ap.add_argument("--drop-attrs", action="store_true", help="Drop original type/radius (write type=3, radius=1.0)")
    ap.add_argument("--eps-scale", type=float, default=0.1, help="Offset scale for deg=4 split (fraction of local child distances)")
    ap.add_argument("--recursive", action="store_true", help="Recurse into subfolders for .swc files")
    ap.add_argument("--root-mode", choices=["parent", "index"], default="parent",
                    help="'parent': root=node with parent<=root_parent_value (default). "
                         "'index': root=node with id=1 (soma convention).")
    args = ap.parse_args()

    in_dir = args.input_dir
    out_dir = args.output_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    files = iter_swc_files(in_dir, recursive=args.recursive)
    total = len(files)
    if total == 0:
        print(f"[WARN] No .swc files found under {in_dir}", file=sys.stderr)
        return 0

    print(f"[INFO] Found {total} .swc file(s) under {in_dir}"
          f"{' (recursive)' if args.recursive else ''}")

    iterator = tqdm(files, total=total, desc="Processing SWC", unit="file") if tqdm else files
    log = (lambda s: tqdm.write(s)) if tqdm else (lambda s: print(s))

    for src in iterator:
        try:
            rel = src.relative_to(in_dir) if args.recursive else src.name
        except Exception:
            rel = src.name
        dst = out_dir / rel
        dst.parent.mkdir(parents=True, exist_ok=True)

        try:
            df = read_swc(src)
            df_clean = clean_swc_tree(
                df,
                root_parent_value=args.root_parent,
                keep_parent_value=args.root_parent,
                max_depth=args.max_depth,
                eps_scale=args.eps_scale,
                keep_attrs=(not args.drop_attrs),
                root_mode=args.root_mode,
            )
            write_swc(df_clean, dst, root_parent_value=args.root_parent)
        except Exception as e:
            log(f"[FAIL] {src}: {e}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
