name: expansion
leaf_noise_sigma: 0.05
leaf_noise_clip: null
sibling_loss_weight: 0.0
use_sibling_matching: False
use_geo_lr_mask: True
use_radial_distance: False
deterministic_expansion: True
use_size_ratio: False