defaults:
  - _self_
  - dataset: neurons # neurons.yaml
  - diffusion: basic # basic.yaml
  - method: expansion # expansion.yaml

reduction:
  type: "depth"
  mode: "stochastic"
  cherry_p: 1.0 
  ensure_progress: True
  root: 0
  contract_root: False
  num_red_seqs: -1
  min_red_frac: 0.0
  max_red_frac: 0.5
  red_threshold: 0

training:
  batch_size: 512 # can adjust based on GPU memory, but does make steps slower on increasing and hence there is a tradoff on updates per unit time
  lr: 1e-3
  num_steps: 500000 
  max_num_workers: 0
  log_interval: 1000 # can make 5K as well
  save_checkpoint: True
  resume: False #"/itet-stor/guptau/net_scratch/dendrite_gen/outputs/2026-03-21/08-51-39/checkpoints/step_60000.pt" # False, True (latest checkpoint), step number, or path to .pt file
  lr_scheduler: "cosine_annealing"              
  scheduler_T_max: ${training.num_steps}  
  scheduler_eta_min: 1e-5          

validation:
  batch_size: 64 # adjust according train/val split - currently only 50 samples in val set
  interval: 50000 # can make 5k
  first_step: 0
  per_graph_size: False
  enable_metrics: False
  enable_plots: True

testing: False # if True, only evaluate on test set

model:
  name: egnn
  num_layers: 6
  feats_dim: 64
  m_dim: 64
  tmd_in_dim: 0
  tmd_hidden_dim: 0
  dropout: 0.1
  norm_feats: True
  global_linear_attn_every: 2
  global_linear_attn_heads: 4
  global_linear_attn_dim_head: 16
  num_global_tokens: 4
  offset_head_hidden: 128
  use_global_fallback_frames: False
  so2_axis: [0., 1., 0.] # z-axis for trees, y-axis for neurons

ema: # can adjust for more stable training, but I haven't had the chance to experiment with it much - working though
  betas: [1]
  gamma: 1.0
  power: 1.0

name: neuron_dataset_experiment_final_3
debugging: False
debugging_max_batches: 50
debugging_dir: "neurons_debug"

wandb: # also working, can log in and use
  logging: True