defaults:
  - _self_
  - dataset: trees_test
  - diffusion: basic
  - method: expansion_oneshot

reduction:
  type: "depth"
  mode: "stochastic"
  cherry_p: 1.0 # imp now with new leaves tracking?
  ensure_progress: True
  root: 0
  contract_root: False
  num_red_seqs: -1
  min_red_frac: 0.0
  max_red_frac: 0.5
  red_threshold: 0

training:
  batch_size: 128
  lr: 5e-4
  num_steps: 40000 # ~200 epochs; considering 1 step = 1 batch
  max_num_workers: 0
  log_interval: 200
  save_checkpoint: True
  resume: False # False, True (latest checkpoint), step number, or path to .pt file
  lr_scheduler: "cosine_annealing"              # Enable cosine annealing
  scheduler_T_max: ${training.num_steps}  # Optional: full cosine cycle length
  scheduler_eta_min: 1e-5          # Optional: minimum learning rate

validation:
  batch_size: 1
  interval: 200
  first_step: 0
  per_graph_size: False
  enable_metrics: False
  enable_plots: True

testing: False # if True, only evaluate on test set

model:
  name: egnn
  num_layers: 6
  feats_dim: 64
  m_dim: 64
  tmd_in_dim: 768
  tmd_hidden_dim: 32
  dropout: 0.1
  norm_feats: True
  global_linear_attn_every: 2
  global_linear_attn_heads: 4
  global_linear_attn_dim_head: 16
  num_global_tokens: 4
  offset_head_hidden: 128
  use_global_fallback_frames: False

ema:
  betas: [1]
  gamma: 1.0
  power: 1.0

name: medium_trees_test_basic_mixed_descriptor_2
debugging: False
debugging_max_batches: 50
debugging_dir: "small_trees_debug"

wandb:
  logging: True