defaults:
  - _self_
  - dataset: tree
  - method: expansion_oneshot

reduction:
  mode: "stochastic"
  cherry_p: 0.8
  ensure_progress: True
  root: 0
  contract_root: False
  num_red_seqs: -1
  min_red_frac: 0.0
  max_red_frac: 0.5
  red_threshold: 0

training:
  batch_size: 64
  lr: 1e-5
  num_steps: 5000000
  max_num_workers: 8
  log_interval: 50000 # considering 50K steps as 1 epoch taking roughly a little over 100 reductions for each graph
  save_checkpoint: True
  resume: False # if True, resume from last checkpoint, if number, resume from that step
  lr_scheduler: "cosine_annealing"              # Enable cosine annealing
  scheduler_T_max: ${training.num_steps}  # Optional: full cosine cycle length
  scheduler_eta_min: 1.0e-8          # Optional: minimum learning rate

validation:
  batch_size: 16
  interval: 50000
  first_step: 0
  per_graph_size: False
  enable_metrics: False
  enable_plots: True

testing: False # if True, only evaluate on test set

model:
  name: egnn
  num_layers: 6
  feats_dim: 32
  m_dim: 32
  dropout: 0.1
  norm_feats: True
  global_linear_attn_every: 2
  global_linear_attn_heads: 4
  global_linear_attn_dim_head: 16
  num_global_tokens: 4
  offset_head_hidden: 64
  use_global_fallback_frames: False

ema:
  betas: [1]
  gamma: 1.0
  power: 1.0

name: small_trees_run_1
debugging: False
debugging_max_batches: 1
debugging_dir: "small_trees_debug"

wandb:
  logging: False
