"""Shared defaults for Plotly cylinder tree rendering."""

DEFAULT_PLOTLY_TEXTURE = "bark"
DEFAULT_PLOTLY_TEXTURE_STRENGTH = 0.2
DEFAULT_PLOTLY_TEXTURE_TARGET_LENGTH_SCALE = 1.0
DEFAULT_PLOTLY_TEXTURE_MAX_AXIAL_SEGMENTS = 24
