"""Shared defaults for Plotly cylinder tree rendering."""

DEFAULT_PLOTLY_TEXTURE = "bark"
DEFAULT_PLOTLY_TEXTURE_STRENGTH = 0.2
DEFAULT_PLOTLY_TEXTURE_TARGET_LENGTH_SCALE = 1.0
DEFAULT_PLOTLY_TEXTURE_MAX_AXIAL_SEGMENTS = 24
DEFAULT_PLOTLY_LEAVES = False
DEFAULT_PLOTLY_LEAF_COUNT = 24
DEFAULT_PLOTLY_LEAF_OPACITY = 0.50
DEFAULT_PLOTLY_LEAF_SCALE = 1.35
DEFAULT_PLOTLY_LEAF_SEED = 0
